### ISSUE TITLE
when can we see the paper of this project?

### ISSUE THREAD

**Issue by Sky10086** [jiajunwu/marrnet#1]

**Comment by jiajunwu** [comment]
It's now available on the project website http://marrnet.csail.mit.edu . Thanks.

**Comment by abhikhanna30** [comment]
Are you going to release the training code?

**Comment by abhikhanna30** [comment]
Also, if say i want to binarize these voxels , what threshold will you say works for your outputs? As i observed the mode of the values in the output 128*128*128 matrix was 0.001
