### ISSUE TITLE
Dataset and pre-train code

### ISSUE THREAD

**Issue by Yuliang-Zou** [jiajunwu/marrnet#2]
Hi @jiajunwu ,

Thanks for sharing the code. 

I wonder if you can share the synthetic dataset that you mentioned in section4.1 and the pre-train code for both the 2.5 sketch estimator and 3D reconstruction model.

**Comment by andrehuang** [comment]
+1, I do hope the code 3d reconstruction (step2) can be shared.

**Comment by Yuliang-Zou** [comment]
@andrehuang I think step2 is already there.

**Comment by jiajunwu** [comment]
Thanks for asking. The step 2 training code is in the repo now.
