### ISSUE TITLE
Reprojection Consistency fine-tuning code

### ISSUE THREAD

**Issue by klnavaneet** [jiajunwu/marrnet#3]
Please share the code for re-projection consistency based loss and optimization.

**Comment by chaowentao** [comment]
How do you use blender?According to your usage ,I can't get the result.
cwt@cwt:~/marrnet/visualization/blender$ blender --background --python render.py -- ../../output/chair_1.mat ../result/ chair_1
Traceback (most recent call last):
  File "convert.py", line 12, in <module>
    assert(filename[-4:] == '.mat')
AssertionError
Traceback (most recent call last):
  File "/home/cwt/marrnet/visualization/blender/render.py", line 179, in <module>
    render_file(file_path, output_dir, output_prefix, 'png')
  File "/home/cwt/marrnet/visualization/blender/render.py", line 14, in render_file
    mat = np.load(tempfilename)
  File "/usr/lib/python3/dist-packages/numpy/lib/npyio.py", line 370, in load
    fid = open(file, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'rende.npy'

Blender quit
Please give me some advie.I want to know the version of Blender.Many thanks.

**Comment by jiajunwu** [comment]
@chaowentao It seems you haven't generated the chair_1.mat yet.

**Comment by chaowentao** [comment]
@jiajunwu Thanke you.I have solve the problem.Probably because of a problem with the file path, I modified the related path settings to run the program.The result of the running is very good.Thank you very much.
